#!/usr/bin/env bash
# Start local PostGIS, apply auth stub + migrations, write .env.
# Prefers Docker Compose; falls back to host psql (e.g. brew postgresql@16 + postgis).
# Local only — not for hosted Supabase.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

pick_port() {
  if command -v lsof >/dev/null 2>&1; then
    if lsof -nP -iTCP:5432 -sTCP:LISTEN >/dev/null 2>&1; then
      echo 5433
      return
    fi
  fi
  if command -v nc >/dev/null 2>&1; then
    if nc -z 127.0.0.1 5432 >/dev/null 2>&1; then
      echo 5433
      return
    fi
  fi
  echo 5432
}

write_env_if_missing() {
  local target="$1"
  local url="$2"
  if [[ -f "${target}" ]]; then
    echo "Keeping existing ${target}"
    return
  fi
  cat >"${target}" <<EOF
# Local Milestone 1 — gitignored. Generated by npm run db:local.
DATABASE_URL=${url}
ALLOW_DEV_AUTH=true
API_PORT=8787
CORS_ORIGINS=http://localhost:5173
OBJECT_STORE=filesystem
UPLOAD_DIR=.uploads
PUBLIC_UPLOAD_BASE_URL=http://localhost:8787/dev-uploads
PUBLIC_APP_URL=http://localhost:5173
PUBLIC_API_URL=http://localhost:8787
VITE_API_URL=http://localhost:8787
VITE_ALLOW_DEV_AUTH=true
EOF
  echo "Wrote ${target}"
}

finish() {
  local url="$1"
  write_env_if_missing "${ROOT}/.env" "${url}"
  write_env_if_missing "${ROOT}/apps/web/.env" "${url}"
  echo
  echo "Local database ready."
  echo "DATABASE_URL=${url}"
  echo "Next: npm run db:seed   then restart the API (npm run dev:api)"
}

# --- Docker Compose path (preferred) ---
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  EXISTING_PORT=""
  if docker compose ps --status running --format '{{.Name}} {{.Publishers}}' 2>/dev/null | grep -q mamdani-ticketer-db; then
    EXISTING_PORT="$(docker compose port db 5432 2>/dev/null | awk -F: '{print $NF}' || true)"
  fi

  if [[ -n "${EXISTING_PORT}" ]]; then
    DB_HOST_PORT="${EXISTING_PORT}"
  else
    DB_HOST_PORT="${DB_HOST_PORT:-$(pick_port)}"
  fi

  export DB_HOST_PORT
  DATABASE_URL="postgres://postgres:postgres@localhost:${DB_HOST_PORT}/mamdani"

  echo "Starting PostGIS (Docker) on localhost:${DB_HOST_PORT} ..."
  if [[ "${DB_HOST_PORT}" == "5433" ]]; then
    echo "note: host port 5432 was in use; using 5433"
  fi

  docker compose up -d

  echo "Waiting for database healthy..."
  for _ in $(seq 1 60); do
    status="$(docker compose ps --format '{{.Health}}' 2>/dev/null | head -1 || true)"
    if [[ "${status}" == "healthy" ]]; then
      break
    fi
    if docker compose exec -T db pg_isready -U postgres -d mamdani >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done

  if ! docker compose exec -T db pg_isready -U postgres -d mamdani >/dev/null 2>&1; then
    echo "error: database did not become ready" >&2
    docker compose ps >&2 || true
    exit 1
  fi

  run_sql_docker() {
    local file="$1"
    echo "Applying ${file} ..."
    docker compose exec -T db psql -U postgres -d mamdani -v ON_ERROR_STOP=1 <"${file}"
  }

  run_sql_docker "db/local/00_auth_stub.sql"
  for f in db/migrations/*.sql; do
    run_sql_docker "${f}"
  done

  finish "${DATABASE_URL}"
  exit 0
fi

# --- Host Postgres fallback (brew postgresql@16 + postgis, etc.) ---
echo "Docker daemon unavailable; trying host psql..."

PSQL_BIN=""
if command -v psql >/dev/null 2>&1; then
  PSQL_BIN="$(command -v psql)"
elif [[ -x /opt/homebrew/opt/postgresql@16/bin/psql ]]; then
  export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
  PSQL_BIN="$(command -v psql)"
fi

if [[ -z "${PSQL_BIN}" ]]; then
  echo "error: Docker is not running and psql is not installed." >&2
  echo "Start Docker Desktop, or: brew install postgresql@16 postgis && brew services start postgresql@16" >&2
  exit 1
fi

if ! pg_isready >/dev/null 2>&1 && ! pg_isready -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then
  echo "error: host Postgres is not accepting connections." >&2
  echo "Start it with: brew services start postgresql@16" >&2
  echo "Or repair/start Docker Desktop and re-run npm run db:local." >&2
  exit 1
fi

# Ensure role + database exist (superuser socket login as current OS user)
psql -d postgres -v ON_ERROR_STOP=1 <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'postgres') THEN
    CREATE ROLE postgres LOGIN SUPERUSER PASSWORD 'postgres';
  ELSE
    ALTER ROLE postgres WITH LOGIN SUPERUSER PASSWORD 'postgres';
  END IF;
END
$$;
SQL

if ! psql -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'mamdani'" | grep -q 1; then
  createdb -O postgres mamdani
fi

DB_HOST_PORT=5432
if ! pg_isready -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then
  if pg_isready -h 127.0.0.1 -p 5433 >/dev/null 2>&1; then
    DB_HOST_PORT=5433
    echo "note: using host port 5433"
  fi
fi

DATABASE_URL="postgres://postgres:postgres@localhost:${DB_HOST_PORT}/mamdani"

# Prefer TCP URL; fall back to socket as current user if password auth fails
run_sql_host() {
  local file="$1"
  echo "Applying ${file} ..."
  if ! psql "${DATABASE_URL}" -v ON_ERROR_STOP=1 -f "${file}" 2>/dev/null; then
    psql -d mamdani -v ON_ERROR_STOP=1 -f "${file}"
  fi
}

run_sql_host "db/local/00_auth_stub.sql"
for f in db/migrations/*.sql; do
  run_sql_host "${f}"
done

finish "${DATABASE_URL}"
